name: "js_platform_dbt_cl"
version: "2.1.0"
config-version: 2
dbt-cloud:
    project-id: 312815
profile: "default"
require-dbt-version: ">=1.6.0"

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "jaffle-data" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  +tags: js_platform_dbt_cl

models:
  +tags: js_platform_dbt_cl
  js_platform_dbt_cl:
    staging:
      +materialized: view
    datamart:
      +materialized: table
  elementary:
    +enabled: true