astrafy:
  target: dev
  outputs:
    # Service account
    dev:
      type: bigquery
      project: "astrafy-gke-dev"
      execution_project: astrafy-gke-dev
      schema: na
      location: "EU"
      method: oauth
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 3
